package com.example.myapplication.domain.model

/**
 * Domain model representing a currency with its exchange rate.
 *
 * @property code ISO 4217 currency code (e.g., "EUR", "USD")
 * @property name Full name (e.g., "Euro", "US Dollar")
 * @property flag Emoji flag for the currency's country
 * @property rateToUsd Exchange rate relative to USD
 * @property position Display order in the converter (lower = higher in list)
 * @property isVisible Whether shown in the converter screen
 */
data class Currency(
    val code: String,
    val name: String,
    val flag: String,
    val rateToUsd: Double,
    val position: Int,
    val isVisible: Boolean = true
)

/**
 * Static currency metadata (names and flags) for all supported currencies.
 */
object CurrencyInfo {

    // Map of currency code -> (name, flag emoji)
    private val currencyData = mapOf(
        "AED" to Pair("UAE Dirham", "\uD83C\uDDE6\uD83C\uDDEA"),
        "AFN" to Pair("Afghan Afghani", "\uD83C\uDDE6\uD83C\uDDEB"),
        "ALL" to Pair("Albanian Lek", "\uD83C\uDDE6\uD83C\uDDF1"),
        "AMD" to Pair("Armenian Dram", "\uD83C\uDDE6\uD83C\uDDF2"),
        "ANG" to Pair("Netherlands Antillean Guilder", "\uD83C\uDDF3\uD83C\uDDF1"),
        "AOA" to Pair("Angolan Kwanza", "\uD83C\uDDE6\uD83C\uDDF4"),
        "ARS" to Pair("Argentine Peso", "\uD83C\uDDE6\uD83C\uDDF7"),
        "AUD" to Pair("Australian Dollar", "\uD83C\uDDE6\uD83C\uDDFA"),
        "AWG" to Pair("Aruban Florin", "\uD83C\uDDE6\uD83C\uDDFC"),
        "AZN" to Pair("Azerbaijani Manat", "\uD83C\uDDE6\uD83C\uDDFF"),
        "BAM" to Pair("Bosnia-Herzegovina Convertible Mark", "\uD83C\uDDE7\uD83C\uDDE6"),
        "BBD" to Pair("Barbadian Dollar", "\uD83C\uDDE7\uD83C\uDDE7"),
        "BDT" to Pair("Bangladeshi Taka", "\uD83C\uDDE7\uD83C\uDDE9"),
        "BGN" to Pair("Bulgarian Lev", "\uD83C\uDDE7\uD83C\uDDEC"),
        "BHD" to Pair("Bahraini Dinar", "\uD83C\uDDE7\uD83C\uDDED"),
        "BIF" to Pair("Burundian Franc", "\uD83C\uDDE7\uD83C\uDDEE"),
        "BMD" to Pair("Bermudan Dollar", "\uD83C\uDDE7\uD83C\uDDF2"),
        "BND" to Pair("Brunei Dollar", "\uD83C\uDDE7\uD83C\uDDF3"),
        "BOB" to Pair("Bolivian Boliviano", "\uD83C\uDDE7\uD83C\uDDF4"),
        "BRL" to Pair("Brazilian Real", "\uD83C\uDDE7\uD83C\uDDF7"),
        "BSD" to Pair("Bahamian Dollar", "\uD83C\uDDE7\uD83C\uDDF8"),
        "BTC" to Pair("Bitcoin", "\u20BF"),
        "BTN" to Pair("Bhutanese Ngultrum", "\uD83C\uDDE7\uD83C\uDDF9"),
        "BWP" to Pair("Botswanan Pula", "\uD83C\uDDE7\uD83C\uDDFC"),
        "BYN" to Pair("Belarusian Ruble", "\uD83C\uDDE7\uD83C\uDDFE"),
        "BZD" to Pair("Belize Dollar", "\uD83C\uDDE7\uD83C\uDDFF"),
        "CAD" to Pair("Canadian Dollar", "\uD83C\uDDE8\uD83C\uDDE6"),
        "CDF" to Pair("Congolese Franc", "\uD83C\uDDE8\uD83C\uDDE9"),
        "CHF" to Pair("Swiss Franc", "\uD83C\uDDE8\uD83C\uDDED"),
        "CLF" to Pair("Chilean Unit of Account", "\uD83C\uDDE8\uD83C\uDDF1"),
        "CLP" to Pair("Chilean Peso", "\uD83C\uDDE8\uD83C\uDDF1"),
        "CNH" to Pair("Chinese Yuan (Offshore)", "\uD83C\uDDE8\uD83C\uDDF3"),
        "CNY" to Pair("Chinese Yuan", "\uD83C\uDDE8\uD83C\uDDF3"),
        "COP" to Pair("Colombian Peso", "\uD83C\uDDE8\uD83C\uDDF4"),
        "CRC" to Pair("Costa Rican Colon", "\uD83C\uDDE8\uD83C\uDDF7"),
        "CUC" to Pair("Cuban Convertible Peso", "\uD83C\uDDE8\uD83C\uDDFA"),
        "CUP" to Pair("Cuban Peso", "\uD83C\uDDE8\uD83C\uDDFA"),
        "CVE" to Pair("Cape Verdean Escudo", "\uD83C\uDDE8\uD83C\uDDFB"),
        "CZK" to Pair("Czech Republic Koruna", "\uD83C\uDDE8\uD83C\uDDFF"),
        "DJF" to Pair("Djiboutian Franc", "\uD83C\uDDE9\uD83C\uDDEF"),
        "DKK" to Pair("Danish Krone", "\uD83C\uDDE9\uD83C\uDDF0"),
        "DOP" to Pair("Dominican Peso", "\uD83C\uDDE9\uD83C\uDDF4"),
        "DZD" to Pair("Algerian Dinar", "\uD83C\uDDE9\uD83C\uDDFF"),
        "EGP" to Pair("Egyptian Pound", "\uD83C\uDDEA\uD83C\uDDEC"),
        "ERN" to Pair("Eritrean Nakfa", "\uD83C\uDDEA\uD83C\uDDF7"),
        "ETB" to Pair("Ethiopian Birr", "\uD83C\uDDEA\uD83C\uDDF9"),
        "EUR" to Pair("Euro", "\uD83C\uDDEA\uD83C\uDDFA"),
        "FJD" to Pair("Fijian Dollar", "\uD83C\uDDEB\uD83C\uDDEF"),
        "FKP" to Pair("Falkland Islands Pound", "\uD83C\uDDEB\uD83C\uDDF0"),
        "GBP" to Pair("British Pound Sterling", "\uD83C\uDDEC\uD83C\uDDE7"),
        "GEL" to Pair("Georgian Lari", "\uD83C\uDDEC\uD83C\uDDEA"),
        "GGP" to Pair("Guernsey Pound", "\uD83C\uDDEC\uD83C\uDDEC"),
        "GHS" to Pair("Ghanaian Cedi", "\uD83C\uDDEC\uD83C\uDDED"),
        "GIP" to Pair("Gibraltar Pound", "\uD83C\uDDEC\uD83C\uDDEE"),
        "GMD" to Pair("Gambian Dalasi", "\uD83C\uDDEC\uD83C\uDDF2"),
        "GNF" to Pair("Guinean Franc", "\uD83C\uDDEC\uD83C\uDDF3"),
        "GTQ" to Pair("Guatemalan Quetzal", "\uD83C\uDDEC\uD83C\uDDF9"),
        "GYD" to Pair("Guyanaese Dollar", "\uD83C\uDDEC\uD83C\uDDFE"),
        "HKD" to Pair("Hong Kong Dollar", "\uD83C\uDDED\uD83C\uDDF0"),
        "HNL" to Pair("Honduran Lempira", "\uD83C\uDDED\uD83C\uDDF3"),
        "HRK" to Pair("Croatian Kuna", "\uD83C\uDDED\uD83C\uDDF7"),
        "HTG" to Pair("Haitian Gourde", "\uD83C\uDDED\uD83C\uDDF9"),
        "HUF" to Pair("Hungarian Forint", "\uD83C\uDDED\uD83C\uDDFA"),
        "IDR" to Pair("Indonesian Rupiah", "\uD83C\uDDEE\uD83C\uDDE9"),
        "ILS" to Pair("Israeli New Sheqel", "\uD83C\uDDEE\uD83C\uDDF1"),
        "IMP" to Pair("Manx pound", "\uD83C\uDDEE\uD83C\uDDF2"),
        "INR" to Pair("Indian Rupee", "\uD83C\uDDEE\uD83C\uDDF3"),
        "IQD" to Pair("Iraqi Dinar", "\uD83C\uDDEE\uD83C\uDDF6"),
        "IRR" to Pair("Iranian Rial", "\uD83C\uDDEE\uD83C\uDDF7"),
        "ISK" to Pair("Icelandic Krona", "\uD83C\uDDEE\uD83C\uDDF8"),
        "JEP" to Pair("Jersey Pound", "\uD83C\uDDEF\uD83C\uDDEA"),
        "JMD" to Pair("Jamaican Dollar", "\uD83C\uDDEF\uD83C\uDDF2"),
        "JOD" to Pair("Jordanian Dinar", "\uD83C\uDDEF\uD83C\uDDF4"),
        "JPY" to Pair("Japanese Yen", "\uD83C\uDDEF\uD83C\uDDF5"),
        "KES" to Pair("Kenyan Shilling", "\uD83C\uDDF0\uD83C\uDDEA"),
        "KGS" to Pair("Kyrgystani Som", "\uD83C\uDDF0\uD83C\uDDEC"),
        "KHR" to Pair("Cambodian Riel", "\uD83C\uDDF0\uD83C\uDDED"),
        "KMF" to Pair("Comorian Franc", "\uD83C\uDDF0\uD83C\uDDF2"),
        "KPW" to Pair("North Korean Won", "\uD83C\uDDF0\uD83C\uDDF5"),
        "KRW" to Pair("South Korean Won", "\uD83C\uDDF0\uD83C\uDDF7"),
        "KWD" to Pair("Kuwaiti Dinar", "\uD83C\uDDF0\uD83C\uDDFC"),
        "KYD" to Pair("Cayman Islands Dollar", "\uD83C\uDDF0\uD83C\uDDFE"),
        "KZT" to Pair("Kazakhstani Tenge", "\uD83C\uDDF0\uD83C\uDDFF"),
        "LAK" to Pair("Laotian Kip", "\uD83C\uDDF1\uD83C\uDDE6"),
        "LBP" to Pair("Lebanese Pound", "\uD83C\uDDF1\uD83C\uDDE7"),
        "LKR" to Pair("Sri Lankan Rupee", "\uD83C\uDDF1\uD83C\uDDF0"),
        "LRD" to Pair("Liberian Dollar", "\uD83C\uDDF1\uD83C\uDDF7"),
        "LSL" to Pair("Lesotho Loti", "\uD83C\uDDF1\uD83C\uDDF8"),
        "LYD" to Pair("Libyan Dinar", "\uD83C\uDDF1\uD83C\uDDFE"),
        "MAD" to Pair("Moroccan Dirham", "\uD83C\uDDF2\uD83C\uDDE6"),
        "MDL" to Pair("Moldovan Leu", "\uD83C\uDDF2\uD83C\uDDE9"),
        "MGA" to Pair("Malagasy Ariary", "\uD83C\uDDF2\uD83C\uDDEC"),
        "MKD" to Pair("Macedonian Denar", "\uD83C\uDDF2\uD83C\uDDF0"),
        "MMK" to Pair("Myanma Kyat", "\uD83C\uDDF2\uD83C\uDDF2"),
        "MNT" to Pair("Mongolian Tugrik", "\uD83C\uDDF2\uD83C\uDDF3"),
        "MOP" to Pair("Macanese Pataca", "\uD83C\uDDF2\uD83C\uDDF4"),
        "MRU" to Pair("Mauritanian Ouguiya", "\uD83C\uDDF2\uD83C\uDDF7"),
        "MUR" to Pair("Mauritian Rupee", "\uD83C\uDDF2\uD83C\uDDFA"),
        "MVR" to Pair("Maldivian Rufiyaa", "\uD83C\uDDF2\uD83C\uDDFB"),
        "MWK" to Pair("Malawian Kwacha", "\uD83C\uDDF2\uD83C\uDDFC"),
        "MXN" to Pair("Mexican Peso", "\uD83C\uDDF2\uD83C\uDDFD"),
        "MYR" to Pair("Malaysian Ringgit", "\uD83C\uDDF2\uD83C\uDDFE"),
        "MZN" to Pair("Mozambican Metical", "\uD83C\uDDF2\uD83C\uDDFF"),
        "NAD" to Pair("Namibian Dollar", "\uD83C\uDDF3\uD83C\uDDE6"),
        "NGN" to Pair("Nigerian Naira", "\uD83C\uDDF3\uD83C\uDDEC"),
        "NIO" to Pair("Nicaraguan Cordoba", "\uD83C\uDDF3\uD83C\uDDEE"),
        "NOK" to Pair("Norwegian Krone", "\uD83C\uDDF3\uD83C\uDDF4"),
        "NPR" to Pair("Nepalese Rupee", "\uD83C\uDDF3\uD83C\uDDF5"),
        "NZD" to Pair("New Zealand Dollar", "\uD83C\uDDF3\uD83C\uDDFF"),
        "OMR" to Pair("Omani Rial", "\uD83C\uDDF4\uD83C\uDDF2"),
        "PAB" to Pair("Panamanian Balboa", "\uD83C\uDDF5\uD83C\uDDE6"),
        "PEN" to Pair("Peruvian Nuevo Sol", "\uD83C\uDDF5\uD83C\uDDEA"),
        "PGK" to Pair("Papua New Guinean Kina", "\uD83C\uDDF5\uD83C\uDDEC"),
        "PHP" to Pair("Philippine Peso", "\uD83C\uDDF5\uD83C\uDDED"),
        "PKR" to Pair("Pakistani Rupee", "\uD83C\uDDF5\uD83C\uDDF0"),
        "PLN" to Pair("Polish Zloty", "\uD83C\uDDF5\uD83C\uDDF1"),
        "PYG" to Pair("Paraguayan Guarani", "\uD83C\uDDF5\uD83C\uDDFE"),
        "QAR" to Pair("Qatari Rial", "\uD83C\uDDF6\uD83C\uDDE6"),
        "RON" to Pair("Romanian Leu", "\uD83C\uDDF7\uD83C\uDDF4"),
        "RSD" to Pair("Serbian Dinar", "\uD83C\uDDF7\uD83C\uDDF8"),
        "RUB" to Pair("Russian Ruble", "\uD83C\uDDF7\uD83C\uDDFA"),
        "RWF" to Pair("Rwandan Franc", "\uD83C\uDDF7\uD83C\uDDFC"),
        "SAR" to Pair("Saudi Riyal", "\uD83C\uDDF8\uD83C\uDDE6"),
        "SBD" to Pair("Solomon Islands Dollar", "\uD83C\uDDF8\uD83C\uDDE7"),
        "SCR" to Pair("Seychellois Rupee", "\uD83C\uDDF8\uD83C\uDDE8"),
        "SDG" to Pair("Sudanese Pound", "\uD83C\uDDF8\uD83C\uDDE9"),
        "SEK" to Pair("Swedish Krona", "\uD83C\uDDF8\uD83C\uDDEA"),
        "SGD" to Pair("Singapore Dollar", "\uD83C\uDDF8\uD83C\uDDEC"),
        "SHP" to Pair("Saint Helena Pound", "\uD83C\uDDF8\uD83C\uDDED"),
        "SLL" to Pair("Sierra Leonean Leone", "\uD83C\uDDF8\uD83C\uDDF1"),
        "SOS" to Pair("Somali Shilling", "\uD83C\uDDF8\uD83C\uDDF4"),
        "SRD" to Pair("Surinamese Dollar", "\uD83C\uDDF8\uD83C\uDDF7"),
        "SSP" to Pair("South Sudanese Pound", "\uD83C\uDDF8\uD83C\uDDF8"),
        "STD" to Pair("Sao Tome and Principe Dobra (pre-2018)", "\uD83C\uDDF8\uD83C\uDDF9"),
        "STN" to Pair("Sao Tome and Principe Dobra", "\uD83C\uDDF8\uD83C\uDDF9"),
        "SVC" to Pair("Salvadoran Colon", "\uD83C\uDDF8\uD83C\uDDFB"),
        "SYP" to Pair("Syrian Pound", "\uD83C\uDDF8\uD83C\uDDFE"),
        "SZL" to Pair("Swazi Lilangeni", "\uD83C\uDDF8\uD83C\uDDFF"),
        "THB" to Pair("Thai Baht", "\uD83C\uDDF9\uD83C\uDDED"),
        "TJS" to Pair("Tajikistani Somoni", "\uD83C\uDDF9\uD83C\uDDEF"),
        "TMT" to Pair("Turkmenistani Manat", "\uD83C\uDDF9\uD83C\uDDF2"),
        "TND" to Pair("Tunisian Dinar", "\uD83C\uDDF9\uD83C\uDDF3"),
        "TOP" to Pair("Tongan Paanga", "\uD83C\uDDF9\uD83C\uDDF4"),
        "TRY" to Pair("Turkish Lira", "\uD83C\uDDF9\uD83C\uDDF7"),
        "TTD" to Pair("Trinidad and Tobago Dollar", "\uD83C\uDDF9\uD83C\uDDF9"),
        "TWD" to Pair("New Taiwan Dollar", "\uD83C\uDDF9\uD83C\uDDFC"),
        "TZS" to Pair("Tanzanian Shilling", "\uD83C\uDDF9\uD83C\uDDFF"),
        "UAH" to Pair("Ukrainian Hryvnia", "\uD83C\uDDFA\uD83C\uDDE6"),
        "UGX" to Pair("Ugandan Shilling", "\uD83C\uDDFA\uD83C\uDDEC"),
        "USD" to Pair("US Dollar", "\uD83C\uDDFA\uD83C\uDDF8"),
        "UYU" to Pair("Uruguayan Peso", "\uD83C\uDDFA\uD83C\uDDFE"),
        "UZS" to Pair("Uzbekistan Som", "\uD83C\uDDFA\uD83C\uDDFF"),
        "VES" to Pair("Venezuelan Bolivar Soberano", "\uD83C\uDDFB\uD83C\uDDEA"),
        "VND" to Pair("Vietnamese Dong", "\uD83C\uDDFB\uD83C\uDDF3"),
        "VUV" to Pair("Vanuatu Vatu", "\uD83C\uDDFB\uD83C\uDDFA"),
        "WST" to Pair("Samoan Tala", "\uD83C\uDDFC\uD83C\uDDF8"),
        "XAF" to Pair("CFA Franc BEAC", "\uD83C\uDF0D"),
        "XAG" to Pair("Silver Ounce", "\uD83E\uDD48"),
        "XAU" to Pair("Gold Ounce", "\uD83E\uDD47"),
        "XCD" to Pair("East Caribbean Dollar", "\uD83C\uDF0E"),
        "XDR" to Pair("Special Drawing Rights", "\uD83C\uDF10"),
        "XOF" to Pair("CFA Franc BCEAO", "\uD83C\uDF0D"),
        "XPD" to Pair("Palladium Ounce", "\u2B50"),
        "XPF" to Pair("CFP Franc", "\uD83C\uDF0F"),
        "XPT" to Pair("Platinum Ounce", "\u2B50"),
        "YER" to Pair("Yemeni Rial", "\uD83C\uDDFE\uD83C\uDDEA"),
        "ZAR" to Pair("South African Rand", "\uD83C\uDDFF\uD83C\uDDE6"),
        "ZMW" to Pair("Zambian Kwacha", "\uD83C\uDDFF\uD83C\uDDF2"),
        "ZWL" to Pair("Zimbabwean Dollar", "\uD83C\uDDFF\uD83C\uDDFC")
    )

    fun getName(code: String): String = currencyData[code]?.first ?: code
    fun getFlag(code: String): String = currencyData[code]?.second ?: "\uD83C\uDFF3\uFE0F"

    // Currencies shown by default on first install
    val defaultCurrencies = listOf("EUR","GBP", "USD", "VND", "INR", "TRY")
}
